### ISSUE TITLE
Regarding the consideration of neglecting recoil force in code design

### ISSUE THREAD

**Issue by mikejwg** [ORNL/AdditiveFOAM#34]
In this code, what are the underlying reasons or considerations behind not taking recoil force into account? Therefore, keyhole can not be predicted via this code.  Thank you very much.

**Comment by streeve** [comment]
AdditiveFOAM does not consider the free surface explicitly; however, it does include options for approximating keyholing (see https://ornl.github.io/AdditiveFOAM/docs/usage on `heatSourceModel`)

**Comment by mikejwg** [comment]
Thanks for your reply.
