### ISSUE TITLE
foamToExaCADict for MultilayerPBF

### ISSUE THREAD

**Issue by mikejwg** [ORNL/AdditiveFOAM#36]
Dear authors,
Please, could you clarify whether by adding a foamToExaCADict file in both Multibeam and MultilayerPBF processes, and setting an execute flag to "on", we can expect the foamToExaCADict to be output or generated? We tried doing this, but no file was produced. Thank you!
John

**Comment by streeve** [comment]
@colemanjs any easy fix?

**Comment by colemanjs** [comment]
Marking this issue as closed since it was confirmed correct in #38 with @LPH0696
