### ISSUE TITLE
How to export ExaCA-related data and apply it to ExaCA calculations

### ISSUE THREAD

**Issue by LPH0696** [ORNL/AdditiveFOAM#38]
Dear authors,
We ran a 4-core parallel computation with a 2-layer AdditiveFoam model. We set the foamToExaCADict in the constant folder. In the generated files, there are layer0 and layer1, and under each layer, there is an ExaCA folder containing files (I presume they correspond to the 4 cores: data_0.csv, ..., data_3.csv). We copied the 4 data_*.csv files from layer0 and the 4 data_*.csv files from layer1 into a single twolayers.txt file, and then read this file in ExaCA through "TemperatureFiles": ["./Temperatures/twolayers.txt"]. However, the calculation results seem unreasonable. We are unsure if our processing method is correct.
![image](https://github.com/user-attachments/assets/e2e2bcb3-5d6f-42db-98be-dc92d0539c6c)

This is the result of one of the ExaCA calculations we ran.
We recompiled and ran the latest version (dated November 8th) of AdditiveFoam. In this latest version, the output requirements for ExaCA have been moved to the System section. After running, we did not find ExaCA output files in layer0 or layer1. Thank you for your help in advance.
![381361a4b101cbd616978809759ce852](https://github.com/user-attachments/assets/8bb91102-f3d0-4ac1-9b8b-639f174b147f)
This is the directory of result files from running examples/multilayerPBF

**Comment by colemanjs** [comment]
@LPH0696  - thank you for your comments. We have have an active PR that will enable users to run coupled AdditiveFOAM-ExaCA tutorials (#39). For testing, you should be able to run this workflow with 'Allrun -withExaCA'.

**Comment by LPH0696** [comment]
Thank you very much for your reply!
Currently, when simulating the calculation of the given examples at the command line using the command “. /Allrun -withExaCA” command at the command line to simulate the computation of the given examples. The examples “AMB2018-02-B” and “multiBeam” run successfully without error messages. However, when running the “ [multiLayerPBF](https://github.com/ORNL/AdditiveFOAM/tree/main/tutorials/multiLayerPBF) ” example, some errors occurred. After outputting only one layer of results, the following error message is displayed:
![7cd5f666c9c6536f523cbf0d274abb83](https://github.com/user-attachments/assets/041e54fe-8f4c-487c-9b73-2e2833f060d8)
Some error messages when running the example “mulitiLayerPBF”.
Here are the outputs of two other examples：
![image](https://github.com/user-attachments/assets/e2e8af63-c6c8-4fa8-bf6f-cd84caaaff95)
This is the output of the example “AMB2018-02-B”
![image](https://github.com/user-attachments/assets/1fc41ec1-92a8-4079-9727-862ba5ff1ddc)
This is the output of the example“multiBeam”

**Comment by colemanjs** [comment]
@LPH0696, I am not able to reproduce this effort in the multiLayerPBF tutorial. Are you using the latest version from PR #39?

Also, can you verify that the path is set correctly for the multiLayer utility?
https://github.com/ORNL/AdditiveFOAM/blob/b0fa8904f5343c4fa5237b2547158928d68ac2f3/tutorials/multiLayerPBF/Allrun#L30

It should point to the path in inst_dir/AdditiveFOAM/applications/utilities/multiLayer/

**Comment by LPH0696** [comment]
Dear authors.
Thank you for your help. After changing the input path to CA, it's ready to run in its entirety.

**Comment by streeve** [comment]
Reopen if needed. In the future, I'd suggest using the Discussions tab for this type of question
