### ISSUE TITLE
The output variable U has an unusually small value.

### ISSUE THREAD

**Issue by LPH0696** [ORNL/AdditiveFOAM#40]
Dear authors，
We ran the Additive FOAM example. It was found that the resultant output of the U variable (aka velocity) had a very small value of 1.2e-39, as shown below, and the flow of fluid was barely noticeable. 
![image](https://github.com/user-attachments/assets/54274b2a-f7f3-445e-882c-1616cc2af6b0)
The result of one of the examples.
We now have new problems that needs your help.
We find that there are two phases in the initial setup (powder phase and solid phase), how is the liquid phase (or fluid) introduced? How do we recognize if the powder is melting? How do we recognize the melt pool?

**Comment by streeve** [comment]
If this is related to the joss review, feel free to ignore me

**Comment by colemanjs** [comment]
The partial differential equations (PDEs) solved in AdditiveFOAM use a mixture-based approach, where material properties are volume-averaged according to the local phase fractions within a finite volume cell. The phase state (solid or liquid) is determined by relationships defined in the constant/thermoPath file. As a cell heats through the freezing range, it transitions to a liquid state, allowing fluid motion driven primarily by Marangoni convection, which is applied as a boundary condition. During cooling, as the cell solidifies through the freezing range, fluid flow is gradually suppressed by a Darcy drag term, reducing velocity to zero as the cell becomes fully solid.

**Comment by LPH0696** [comment]
Thank you very much for your reply. After setting nOuterCorrectors to 1, we can see in the output that there is variable U output.

**Comment by colemanjs** [comment]
Great! Marking this issue as closed.
