### ISSUE TITLE
How to increase the output of additivefoam?

### ISSUE THREAD

**Issue by LPH0696** [ORNL/AdditiveFOAM#43]
Dear Authors，
We modified the file createFields.H located in the directory additiveFOAM/applications/solvers/additivefoam to add output about temperature gradients. After recompiling there is still still no relevant output. I kindly ask you to point out our error. We look forward to and appreciate your response!
![image](https://github.com/user-attachments/assets/3a2d3f61-a5da-4618-895f-dbbc0ae97dc4)
This is the part we added.

**Comment by colemanjs** [comment]
@LPH0696 - this is not an AdditiveFOAM-specific issue. Assuming you are updating these fields every time step, there is nothing immediately wrong with this implementation of calculating and writing the temperature gradient and cooling rate. If you need assistance with additional features, please open a discussion.
