### ISSUE TITLE
Undesired behavior of heat source normalization at mesh boundaries

### ISSUE THREAD

**Issue by colemanjs** [ORNL/AdditiveFOAM#5]
The heat source normalization scales the total input power based in the integrated volume. This is a reasonable approach when the laser is completely contained in the physical domain, however, not when we start to scan outside of the mesh.

Since we have analytical forms of the normalization factors, when should probably calculate this based on the volume of the heat source in the physical domain. The rescaling to this normalized volume should fall out naturally.

**Comment by streeve** [comment]
@kincaidkc ?

**Comment by colemanjs** [comment]
Resolved in #15
